# Generated by Django 4.2.7 on 2023-11-10 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalnode',
            name='CompletedAt',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Description',
            field=models.CharField(default='Your Goal Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Height',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Motivation',
            field=models.CharField(default='Your Goal Motivation', max_length=5000),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='StartedAt',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Subtask',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Title',
            field=models.CharField(default='Goal-X', max_length=500),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='ToStartAt',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='X',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='goalnode',
            name='Y',
            field=models.IntegerField(default=100),
        ),
    ]
