# Generated by Django 4.2.7 on 2023-11-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0004_alter_graphflow_adjlist_alter_graphflow_nodecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalnode',
            name='Status',
        ),
        migrations.AddField(
            model_name='goalnode',
            name='State',
            field=models.CharField(default='not-started', max_length=30),
        ),
    ]
