# Generated by Django 4.2.7 on 2023-11-10 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0005_remove_goalnode_status_goalnode_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalnode',
            name='TerminatedAt',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
