# Generated by Django 4.2.7 on 2023-11-12 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0006_goalnode_terminatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphflow',
            name='AdjList',
            field=models.CharField(default='"[]"', max_length=5000),
        ),
    ]
