# Generated by Django 4.2.7 on 2023-11-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalTracker', '0007_alter_graphflow_adjlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('TaskId', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='Task-X', max_length=500)),
                ('Description', models.CharField(default='Your Sub-Task Description', max_length=1000)),
                ('Motivation', models.CharField(default='Your Sub-Task Motivation', max_length=5000)),
                ('State', models.CharField(default='not-started', max_length=30)),
                ('CreatedAt', models.DateField(auto_now_add=True)),
                ('EditedAt', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='graphflow',
            name='AdjList',
            field=models.CharField(default='[]', max_length=5000),
        ),
    ]
